# Generated by Django 4.1 on 2022-08-24 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music_player_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('music_player_api', '0003_song_audio_file_song_cover_img_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=music_player_api.utils.upload_audio_to, validators=[music_player_api.utils.validate_is_music, music_player_api.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=music_player_api.utils.upload_coverimg_to, validators=[music_player_api.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=music_player_api.utils.upload_avatar_to, validators=[music_player_api.utils.validate_file_size]),
        ),
    ]
