# Generated by Django 4.1 on 2022-08-27 17:58

from django.db import migrations, models
import music_player_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('music_player_api', '0004_alter_playlist_added_by_alter_song_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=music_player_api.utils.upload_thumbnail_to, validators=[music_player_api.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='genres', to='music_player_api.song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', through='music_player_api.SongPlaylist', to='music_player_api.song'),
        ),
    ]
